name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag roweluchi/helm3:latest   
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}            
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: roweluchi/helm3:latest